config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'


  resources :user_sessions, only: [:create, :destroy]
  resources :users do
    member do
      put :follow
    end
  end

  resources :posts do
    member do
      put :like #PUT posts/1/like -> posts_controller def like
      post :comment #POST posts/1/comment -> posts_controller def comment
    end
  end

  resources :profiles, param: :name, only: [:show, :edit, :update], constraints: { :name => /[0-z\.]+/ }

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/img_uploader.rb
class ImgUploader < CarrierWave::Uploader::Base
  storage :file

  def store_dir
    "#{Rails.root}/public/#{model.class.name.downcase}"
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img_path, ImgUploader

  belongs_to :user
  has_many :likes
  def has_like(user)
    self.likes.where(user_id: user.id).count != 0
  end

  def like_toggle(user)
    if has_like(user)
      ::Like.where(post: self, user: user).destroy_all
    else
      ::Like.create(post: self, user: user)
    end
  end

  has_many :comments

  def add_comment(user, contents)
    ::Comment.create(post: self, user: user, contents: contents)
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :profile_img, ImgUploader

  has_many :posts
  has_many :likes
  has_many :comments
  has_many :followers, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: /@/
  validates :password, presence: true
  validates_length_of :password, minimum: 6

  def valid_profile_img
    if self.profile_img.present?
      self.profile_img
    else
      'user.png'
    end
  end

  def unfollow(user)
    Relationship.where(follower: self, following: user).destroy_all
  end

  def following?(user)
    Relationship.find_by(follower: self, following: user).present?
  end

  def follow_toggle(user)
    if following?(user)
      unfollow(user)
    else
      Relationship.create(follower: self, following: user)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception
  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('id desc')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new

  end

  # GET /posts/1/edit
  def edit
  end

  def like
    @post.like_toggle(current_user)
    # redirect_back_or_to post_path(@post)
    render partial: 'like.js', layout:false, locals:{post: @post}
  end

  def comment
    contents = params[:comment]
    @post.add_comment current_user, contents
    # redirect_back_or_to post_path(@post)
    render partial: 'comment.js', layout:false, locals:{post: @post}
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to profile_path(current_user.name), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content, :text, :img_path)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
    @posts = @user.posts.order("id desc")
  end

  def edit

  end

  def update

  end

  private
  def set_user
    @user = User.find_by(name: params[:name])
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:name], params[:password])
      redirect_back_or_to root_path, notice: '로그인 성공'
    else
      flash.now[:alert] = '로그인 실패'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to :login, notice: '로그아웃!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token #postman 테스트시 csef_token 인증제거
  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow]

  # GET /users
  # GET /users.json
  def index
    #포스팅의 리스트
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #리스트 중의 상세 정보처리
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    #if 지금 들어온 유저가 == edit 하고 싶은 유저이면


  end

  # POST /users
  # POST /users.json
  def create
    p = user_params
    @user = User.new(p)

    respond_to do |format|
      if @user.save
        # 회원가입 후에 바로 로그인이 되도록 한다
        # login(p[:name], p[:password])
        # format.html { redirect_to users_path}

        # 회원가입 후에 로그인 페이지로 넘어간다
        format.html { redirect_to login_path, notice: 'User was successfully created. you can login now' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #프로필수정
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path(@user.name), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    #회원탈퇴
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    current_user.follow_toggle(@user)
    redirect_back_or_to profile_path(@user.name)
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :password, :profile_img)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<style>
  .footer > div > .col {
    padding-top: 10px;
  }
  .footer div > a {
    color: grey;
    display: inline-block;
    height: 100%;
    width: 100%
  }
</style>


<div class="footer fixed-bottom text-center">
  <div class="row">
    <div class="col">
      <a href="<%= root_path %>">
        <i class="fa fa-2x fa-home">
        </i>
      </a>
    </div>

    <div class="col">
      <a href="<%=  %>">
        <i class="fa fa-2x fa-search">
        </i>
      </a>
    </div>

    <div class="col">
      <a href="<%= new_post_path %>">
        <i class="fa fa-2x fa-camera-retro">
        </i>
      </a>
    </div>

    <div class="col">
      <a href="<%=  %>">
        <i class="fa fa-2x fa-heart-o">
        </i>
      </a>
    </div>

    <div class="col">
      <a href="<%= profile_path(current_user.name) %>">
        <i class="fa fa-2x fa-user">
        </i>
      </a>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">SNUSTA</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if logged_in? %>
          <li class="nav-item">
            <%= link_to '프로필', profile_path(current_user.name), class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to '로그아웃', :logout, method: :delete, class: 'nav-link' %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to '회원가입', new_user_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '로그인', :login, class: 'nav-link' %>
          </li>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snusta</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<% if logged_in? %>
    <%= render 'layouts/header' %>

<% else %>

<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, msg| %>
          <% if name=='alert'%>
              <div class="alert alert-danger" role="alert">
                <%=msg%>
              </div>
          <% else %>
              <div class="alert alert-info" role="alert">
                <%=msg%>
              </div>
          <% end %>
      <% end %>
    </div>
    <div class="col-12 frame">
      <%= yield %>
    </div>
  </div>
</div>

<% if logged_in? %>
    <%= render 'layouts/footer' %>

<% else %>

<% end %>
</body>
</html>

app/views/posts/_comment.html.erb
<table class="comment-table" id="comments-<%=post.id%>" >
  <tbody>
  <% post.comments.each do |comment| %>
      <tr>
        <td class="commenter" style="padding-left: 16px; text-decoration-color: #666666"><%= comment.user.name %></td>
        <td class="comment" style="padding-left: 8px"><%= comment.contents %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/_comment.js.erb
$("#comments-<%=post.id%>")
    .html("<%= j render(partial: 'comment.html.erb', locals:{post: post}) %>")
$("#comment-<%=post.id%>").val("")

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="post-text">
      <%= form.label :title, style: 'width:100%'  %>
    </div>

    <div class="post-text-body">
      <%= form.text_field :title, id: :post_title, style: 'width:100%'  %>
    </div>

    <div class="post-text">
      <%= form.label :content, style: 'width:100%'  %>
    </div>

    <div class="post-text-body">
      <%= form.text_area :content, id: :post_content, style: 'width:100%' %>
    </div>

    <div class="post-text">
      <%= form.label :img_path %>
    </div>

    <div>
      <%= form.file_field :img_path %>
    </div>

    <div class="actions">
      <%= form.submit "포스팅하기", class: 'btn btn-primary signup-submit'%>
    </div>
<% end %>

app/views/posts/_like.html.erb
<%= link_to like_post_path(post.id), id: "like-#{post.id}", method: :put, remote: true do %>
    <% if post.has_like(current_user) %>
        <i class="fa fa-heart fa-2x" style="color:red"></i>
    <% else %>
        <i class="fa fa-heart-o fa-2x" style="color:red"></i>
    <% end %>
<% end %>

app/views/posts/_like.js.erb
$("#like-<%=post.id%>")
    .html("<%= j render(partial: 'like.html.erb', locals:{post: post})%>")

app/views/posts/_post.html.erb
<div class="row justify-content-center">
  <div class="col-xs-10 col-sm-10 col-md-8 col-lg-6" style="margin-top: 20px">
    <div class="card">
      <div class="card-title">
        <span>
          <%= image_tag post.user.valid_profile_img, class: 'img rounded-circle', style: 'width:40px; height:40px; margin-top:12px; margin-left:12px'%>
        </span>
        <span>
          <%= post.user.name %>
        </span>
        <hr>
      </div>

      <div class="card-body">
        <%= image_tag post.img_path,
                      class: 'card-img-top',
                      style: 'width:100%; height:auto;' %>
        <hr>
        <div class="card-text">
          <%= render partial: 'like.html.erb', locals:{post: post} %>
        </div>
        <h4 class="card_body"><%= post.title %></h4>
        <p class="card-text"><%= post.content %></p>
        <p class="card- text">
          <small class="text-muted">
            <%= "#{time_ago_in_words(post.created_at)} 전" %></small>
        </p>
      </div>
        <%= render partial: 'comment.html.erb', locals:{post: post} %>
      <hr>
      <%= form_tag comment_post_path(post), method: :post, class: 'comment-box', remote: true do %>
          <%= text_field_tag :comment, nil, class: 'form-control', id: "comment-#{post.id}" , placeholder: '댓글쓰기..' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12" style="padding-left: 10%;
    padding-right: 10%;">
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h3>새로운 게시물 올리기</h3>



<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'post', post: @post  %>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-sm-2 col-lg-2 col-md-2 col-xs-2">
    <%= image_tag @user.profile_img, style: 'border-radius:50%;width:100%' %>
  </div>
  <div class="col-sm-8 col-lg-8 col-md-8 col-xs-6 profile-text">
    <a><%= @user.name %>의 프로필</a>
    <% if current_user == @user %>
        <%= link_to '프로필 편집', edit_user_path(@user), class: "btn btn_default profile-edit" %>
    <% else %>
        <%= link_to follow_user_path(@user), method: :put, remote: true do %>
            <% if current_user.following?(@user) %>
                <button class="btn btn-default" style="background: #ffffff;border: solid 1px #dbdbdb;">
                  팔로잉
                </button>
            <% else %>
                <button class="btn btn-primary">팔로우</button>
            <% end %>
        <% end %>
    <% end %>
    <div class="col-sm-8 col-lg-8 col-md-8 col-xs-6 profile-text">
    <span class="profile-text">
      게시물 <%= @user.posts.size %>
    </span>
      <span class="profile-text">
      팔로우 0
    </span>
      <span class="profile-text">
      팔로워 0
    </span>
    </div>
  </div>
</div>

<div class="profile-body">
  <div class="row">
    <% @posts.each do |post| %>
        <a href="<%= post_path(post) %>" class="col-lg-4 col-md-4 col-sm-4 col-xs-4 photo-body" style="border:olivedrab sold 1px">
          <%= image_tag post.img_path.url, style: 'width:100%' %>
        </a>
    <% end %>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <div class="signin-field">
      <%= text_field_tag :name, nil, class: 'form-control', placeholder:"사용자이름" %>
    </div>
    <div class="signin-field">
      <%= password_field_tag :password, nil, class: 'form-control', placeholder:"비밀번호" %>
    </div>
    <div class="actions">
      <%= submit_tag "로그인", class: 'btn btn-primary signin-submit' %>
    </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container signup text-center">
  <div class="table table-bordered signup-inner">
    <h1><strong> SNUSTA </strong></h1>
    <br/>

    <%= render 'form', user: @user %>
  </div>

  <div class="signin-inner-bottom">
  계정이 없으신가요? <%= link_to ' 가입하기', new_user_path %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class:'form-group') do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="signup-field">
    <%= form.email_field :email, class: 'form-control', placeholder:"이메일주소" %>
  </div>

  <div class="signup-field">
    <%= form.text_field :name, class: 'form-control', placeholder:"사용자이름" %>
  </div>

  <% if action_name == 'edit' %>
    <div class="signup-field">
      <%= form.file_field :profile_img, class: 'form-control', placeholder: "프로필사진" %>
    </div>
  <% end %>

  <div class="signup-field">
    <%= form.password_field :password, class: 'form-control', placeholder:"비밀번호" %>
  </div>

  <div class="actions">
    <% if action_name == 'new'%>
        <%= form.submit "가입", class: 'btn btn-primary signup-submit'%>
    <% else %>
        <%= form.submit "수정", class: 'btn btn-primary signup-submit'%>
    <% end %>
  </div>

  <div class="signup-text">
    가입하면 SNUSTA의 약관 및 개인정보 처리 방침에 동의하게 됩니다.
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td style="word-break:break-all;"><%= user.name %></td>
        <td><%= link_to '보기', user, class: 'btn btn-primary' %></td>
        <td><%= link_to '수정', edit_user_path(user), class: 'btn btn-warning' %></td>
        <td><%= link_to '삭제', user, method: :delete, data: { confirm: '정말 삭제할거니?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '유저생성', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<div class="container signup text-center">
<div class="table table-bordered signup-inner">
  <h1><strong> SNUSTA </strong></h1>
  <br/>
  <div class="signup-title">
    <h6>
      친구들의 사진과 동영상을 보려면 가입하세요
    </h6>
  </div>

  <%= render 'form', user: @user %>
</div>

<div class="signup-inner-bottom">
  이미 계정이 있으신가요? <%= link_to ' 로그인', :login %>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>